WRITE_LOGS_TO_GOOGLE_DRIVE = True
DEVICE = "cpu"

SOS_TOKEN = 0
EOS_TOKEN = 1
UNK_TOKEN = 2
PAD_TOKEN = 3

MAX_LENGTH = 20
MAX_SEQ_LENGTH = MAX_LENGTH+2 # 2 for EOS_TOKEN and SOS_TOKEN

BATCH_SIZE = 100

TRAIN_PROP = 0.64
VALID_PROP = 0.16
TEST_PROP = 0.2

HIDDEN_SIZE = 60
LEARNING_RATE = 0.001
TEACHER_FORCING_RATIO = 0.5